### ISSUE TITLE
No UWP

### ISSUE THREAD

**Issue by mediaexplorer74** [johnnysbug/TwentyFortyEight#1]
Hi, after 8 years :)

I detected that no UWP target.

Does Monotouch10 has no support of UWP (WinRT)? =)

**Comment by johnnysbug** [comment]
I almost forgot all about this project! Thanks for bringing back some good memories.

I have no plans to update this project, but now that you reminded me about it, I think I might make a version in Flutter!

**Comment by mediaexplorer74** [comment]
> I almost forgot all about this project! Thanks for bringing back some good memories.
> 
> I have no plans to update this project, but now that you reminded me about it, I think I might make a version in Flutter!

Ok. Cool :) 
Well, Flutter supports multi-platforms as I know. I subscribed to your github channel for controlling FlutterTwentyFortyEight codename.
Best,
MediaExplorer
